services:
  backend:
    build: ./backend
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    # --- ADD THIS LINE ---
    # Explicitly use the default bridge network for maximum compatibility.
    network_mode: bridge

  frontend:
    build:
      context: ./frontend
    ports:
      - "3005:80"
    depends_on:
      - backend
    # Keep the restart policy, as it's still good practice.
    restart: unless-stopped
    # --- ADD THIS LINE ---
    # Ensure the frontend is on the same network.
    network_mode: bridge

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    # --- ADD THIS LINE ---
    # Ensure redis is on the same network.
    network_mode: bridge